apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-eks-ecr-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-eks-ecr-app
  template:
    metadata:
      labels:
        app: hello-eks-ecr-app
    spec:
      containers:
      - name: hello-eks-ecr-app
        image: 202516164458.dkr.ecr.ap-south-1.amazonaws.com/java-app:latest
        ports:
        - containerPort: 8080
